
// This changes the background color for the graphs
export const graphColor = '#42ecc4'

//Link to images for Parcel
import bonzerDisPath from './Images/Bonzer/BonzerDis.png'
import bonzerLogoPath from './Images/Bonzer/BonzerLogo.png'
import bwDisPath from './Images/BW/BWDis.png'
import bwLogoPath from './Images/BW/BWLogo.png'
import feverDisPath from './Images/Fever/FeverDis.png'
import feverLogoPath from './Images/Fever/FeverLogo.png'
import peregrineDisPath from './Images/peregrine/PeregrineDis.png'
import peregrineLogoPath from './Images/peregrine/PeregrineLogo.png'
import rookieDisPath from './Images/Rookie/RookieDis.png'
import rookieLogoPath from './Images/Rookie/RookieLogo.png'
import zeusDisPath from './Images/Zeus/ZeusDis.png'
import zeusLogoPath from './Images/Zeus/ZeusLogo.png'
import grabbitDisPath from './Images/Grabbit/GrabbitDis.png'
import grabbitLogoPath from './Images/Grabbit/GrabbitLogo.png'
import protonDisPath from './Images/Proton/ProtonDis.png'
import protonLogoPath from './Images/Proton/ProtonLogo.png'
import fredRubbleDisPath from './Images/FredRubble/FredRubbleDis.png'
import fredRubbleLogoPath from './Images/FredRubble/FredRubbleLogo.png'
import semiProDisPath from './Images/SemiPro12/SemiProDis.png'
import semiProLogoPath from './Images/SemiPro12/SemiProLogo.png'
import dfrDisPath from './Images/DFR/DFRDis.png'
import dfrLogoPath from './Images/DFR/DFRLogo.png'
import tLowDisPath from './Images/T-Low/T-LowDis.png'
import tLowLogoPath from './Images/T-Low/T-LowLogo.png'

// All surfboard information here. If a board has a value for the graph, use graphColor as a value, other wise use '' if null.
export const boards = [
  { id: 1, name: 'Bonzer Shelter', image: bonzerDisPath, imageLogo: bonzerLogoPath, boardDesc:'\“Since 1969 only a few miles and some of California\’s best point breaks separated Al Merrick and The Campbell Brothers, Malcolm and Duncan.  Unbeknown to most, Al and Malcolm began working together in 1985, when Malcolm came on board and shaped for Al CI for over 20 years.  now 30 years on, a design offering is born out of that experience and mutual respect. The Shelter model is our contemporary Bonzer 5 shortboard.  It\’s name was inspired by the 2001 film, Shelter by Chris Malloy and Moonshine Conspiracy. \
  We provided a 6\’2\″ and a 6\’4\″ for the film. The boards were ridden by Taylor Knox, Donovan Frankenreiter, and a cast of visiting surfers.  The Shelter is primarily a squash tail, and can be custom ordered with a swallow, round pin, or thumb tail.  It is a versatile board that works well in all conditions.  When deciding on size, go with your favorite dimensions, taking in consideration the conditions and type of waves you anticipate using the board for. Utilizing the Bonzer\
  5 system, which we have developed and refined over the last 34 years, the Shelter provides quick easy rail to rail transition, and unparalleled drive out of turns.  It also maintains speed exceptionally well through cutbacks, and has been known to have an uncanny ability to navigate through the barrel.  We have been working for years toward getting the Bonzer\
  fully into the mix at the highest levels; with CI that time has come.  Have at it and enjoy the Bonzer Experience.\” Malcolm and Duncan Campbell \
  The goal of this dynamic collaboration is to bring the Bonzer, one of surfing\’s most unique and original designs, to the forefront and to continue CI\’s tradition of surfers building quality surfboards.\
  Available stock in grey, green, blue, and clear.', wsbKnee: graphColor, wsbHead: '', wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor },
  { id: 2, name: 'Black and White', image: bwDisPath, imageLogo: bwLogoPath, boardDesc:'An all around, high performance shortboard designed for down the line speed and easy rail-to-rail transitions, the Black & White is based on a favorite hand shape Britt Merrick made Dane Reynolds for Santa Barbara area point breaks. Dane related its feel to a good MBM. The Black & White has a fairly low entry rocker, a staged flat-ish section between the feet, and an accelerated kick out the tail. A single concave runs the length of the board, is deepest near the front fins and shallows into a\ hint of vee exiting the tail block. A flat deck design, the Black & White offers improved flex characteristics, a solid under-your-feet feel, and full rails. The board should be ridden about your same height to 2\″ longer than you are tall. Because of the flat deck ride the board 1/8 \” thinner than your \
  normal shortboard to keep the same general volume. The Black & White is suitable for most surfers in most types of surf where a shortboard is appropriate', wsbKnee: '', wsbHead: graphColor, wsbDouble:graphColor,waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:'', wavePowerWeak:'', wavePowerMedium:'', wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 3, name: 'Fever', image: feverDisPath, imageLogo: feverLogoPath, boardDesc:'The Fever has its roots in Al Merrick\’s trusted and proven high performance short board designs. The goal in designing this board with Mike Andrews and Patrick Gudauskas was to create a more accessible tour level performance board that anyone who jumped onto it would \“instantly feel the speed and zest \
   for creativity.\” Borrowing Pat\’s favorite elements of the Proton, Rookie and MBM, and combining them with a subtle single concave and lower rocker resulted in a board with a huge sweet spot. With a slightly more parallel outline and forgiving rocker the Fever has proven to be an all-around design that excels in a wide range of conditions and wave types. The Fever also has responded really well to the FlexBar Technology- \“ I think because it\’s such a fast board, the Flexbar technology gives it extra pop and flair and is a nice compliment to the relatively simple outline\”.', wsbKnee: graphColor, wsbHead: '', wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:graphColor, waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 4, name: 'Peregrine', image: peregrineDisPath, imageLogo: peregrineLogoPath, boardDesc:'Named after the fast and powerful falcon that tends to breed on coastal cliffs. This new model connects with the board\’s design for fast, powerful surfing and reflects Dane and Courtney\’s interest in falconry. Four-channels fuel this all around high performance shortboard suitable for all\ wave types. Designed for maximum down the line speed, quick transitions, and big rail turns. The peregrine has a low entry rocker that\’s accelerated through the back. The rail rocker is low but with ample break around the front fins and staged by the exit of the channels, creating extreme release near the trailing fin and off the tail. Center rocker is straighter and fast with the effect being exaggerated by the deep channels running out the back.\
  The channels sit within a generous single concave that runs the length of the board and goes flat at the tail block. The flat deck provides positive flex patterns, volume distribution and feel under the feet. Should be ordered an 1/8th of an inch thinner than a customer\’s usual thickness. (i.e. If the customer usually rides a board with a 2 1/2 center thickness, they should order The Peregrine at 2 3/8 and can expect it to have the same general rail thickness, feel and flotation as a board that is 2 1/2). Rails are round, medium to full. Designed to work best in waist to ceiling high surf. Ride this board your same height up to a couple inches longer. Also makes a good smaller wave board when ordered shorter and wider. *ALL Peregrines come stock with four channels, and are thruster only.', wsbKnee: graphColor, wsbHead: graphColor, wsbDouble:graphColor,waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:graphColor, waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 5, name: 'Rookie', image: rookieDisPath, imageLogo: rookieLogoPath, boardDesc:'First seen on the WCT tour in 2010, the Rookie has been rediscovered by our entire CT team this year; Seabass, Kelly, Adriano, Lakey, Bianca, Sage and Kai all have won heats on the new Rookie 15. Ridden shorter and wider than the original, the Rook 15 is the ultimate contest workhorse.  Single concave throughout, the Rook 15 works best when on rail. Ride this board your same height to 2” longer.', wsbKnee: graphColor, wsbHead: graphColor, wsbDouble:graphColor,waveBreakPoint:'',waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:'', waveSkillExpert:graphColor},
  { id: 6, name: 'Zeus', image: zeusDisPath, imageLogo: zeusLogoPath, boardDesc:'The CI team calls the Zeus \“A quick and loose all-around performance shortboard\”. The bottom contours are very light single entry, to double concave through the fins, to concave vee exit. The Zeus can be ridden as a squash, swallow or round pin in waves from waist to ceiling high.  Originally released in 2014, this board is now custom order only. Ride this board your same height to 2″ longer.', wsbKnee: graphColor, wsbHead: '', wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 7, name: 'Grabbit', image: grabbitDisPath, imageLogo: grabbitLogoPath, boardDesc:'Jordy looks to his Girabbit design when the waves have some push. Best used as all-around shortboard for above average surf. Single concave throughout means the Girabbit works best when on rail. A fairly aggressive tail curve allows for tight radius turns. Ride this board your same height to 3″ longer than you are tall. Jordy is 6’3″ 190 and rides his Girabbit 6’3″ x 19 1/4 x 2 5/8 @ 33.1L Ride this board 1″ to 3″ longer than you are tall.', wsbKnee: '', wsbHead: graphColor, wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 8, name: 'Proton', image: protonDisPath, imageLogo: protonLogoPath, boardDesc:'Voted the 2009 board of the year by SIMA, The Proton is a result of Dane’s design work in late 2007. Still Dane’s go-to board in good pockety surf, the Proton is the choice for advanced surfers everywhere. Original and truly unique from any other board in our line, this board has continuous rocker throughout. The bottom consists of a deep single concave, and full rails. Dane normally rides a 2 3/8″ and orders his Protons at 2 1/4″, so order yours a 1/8″ thinner. Ride this board about 1″ to 3″ longer than you are tall. As of 2012 this board is CUSTOM ONLY', wsbKnee: graphColor, wsbHead: graphColor, wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:''},
  { id: 9, name: 'FredRubble', image: fredRubbleDisPath, imageLogo: fredRubbleLogoPath, boardDesc:'The Fred Rubble is actually quite a bit different than my other boards. It has a lower entry rocker and a wider outline. It has more volume than a Proton, but it isn’t really short and chunky like a Dumpster Diver. It’s just a fun board for waves from waist high to a little over\
   head. I’ve been riding mine two inches shorter than my standard shortboard and 1/4 inch wider. For example, my standard shortboard is a 5’11″ x 18 3/8″ x 2 3/16″ Proton and I ride my Fred Rubble as a 5’9″ x 18 5/8″ x 2 3/16″. So I’d recommend for you a 5’11″ if your normal board is a 6’1″. – Conner Coffin Features single to double concave and comes standard in a squash tail. A contest favorite of Kelly Slater’s as a round tail five-fin EPS/Epoxy Designed to be ridden about the same length as you are tall +/- 1', wsbKnee: graphColor, wsbHead: '', wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 10, name: 'SemiPro', image: semiProDisPath, imageLogo: semiProLogoPath, boardDesc:'(nose) outline and the wide point just a little behind center. The main purpose of this design change (relative to other performance boards)  was to allow for more forward volume which translates to easier paddling and wave catching while still accommodating a short rail for tight arcs. As a Round Tail the SP12 has proven to be one of our most popular step-up boards. Designed to be ridden the same length you are tall, or up to 2″ longer', wsbKnee: graphColor, wsbHead: graphColor, wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:'', wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:''},
  { id: 11, name: 'DFR', image: dfrDisPath, imageLogo: dfrLogoPath, boardDesc:'No, not the “Dane Fred Rubble” the DFR is a design from Dane freaking Reynolds. First ridden in 2012 and a staple on the world tour, the DFR is an ultra-modern short board, the plan-shape allows for a short rail line while maintaining drive. The bottom is predominately single concave and features an aggressive flip in exit rail rocker. A full outline provides enough volume to ride the DFR about the same length as your height. This short board is not only ready for big airs but also allows for the heaviest carves you can lay down. Designed to be ridden approximately the same length as you are tall Dane rides his DFR his own height. 6’0″ x 19″ x 2 3/8″', wsbKnee: graphColor, wsbHead: '', wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:'',waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor},
  { id: 12, name: 'T-Low', image: tLowDisPath, imageLogo: tLowLogoPath, boardDesc:'R&D on the T-Low began with Tanner Gudauskas seeking a lower rockered shortboard and has resulted in an ultra-forgiving all-around performance board. The plan shape of the T-Low takes a different path than the extreme curves in the DFR and Proton by utilizing medium entry and low exit rockers.\
   T-Low bottom contours combine single concave at the 12” mark to flat exit through the back fin. The rails are tapered so consider riding this board 1/16” thicker than your DFR, Rubble, Proton, Rookie, etc. The T-Low has proven to be a unique design, being user friendly and still meeting World Tour requirements as evident by Tanner’s surfing and Dane Reynolds riding a T-Low prototype to a 2012 CT final in France. Tanner says, “If you could take one board on a trip this would be it.” Ride the T-low your same height up to 2″ longer than you are tall.', wsbKnee: graphColor, wsbHead: '', wsbDouble:'',waveBreakPoint:graphColor,waveBreakReef:graphColor,waveBreakBeach:graphColor, wavePowerWeak:'', wavePowerMedium:graphColor, wavePowerStrong:graphColor, waveSkillNovice:'', waveSkillIntermediate:graphColor, waveSkillExpert:graphColor}
];
